import { expect, test } from '@playwright/test';
import { selectInstance } from './designer-helpers';

test('prefab folders hide templates, navigate with breadcrumbs and follow Edit prefab', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?designer=1'); await expect(page.locator('#loading')).toBeHidden();
  await page.getByRole('button', { name: 'Toggle prefab designer', exact: true }).click();
  const browser = page.getByRole('region', { name: 'Prefab browser', exact: true });
  for (const category of ['Characters', 'Objects']) await expect(browser.getByRole('button', { name: `Open ${category} folder` })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Pointlesh properties', exact: true })).toHaveCount(0);
  await browser.getByRole('button', { name: 'Open Characters folder' }).click();
  await expect(browser.locator('[data-prefab-id]')).toHaveCount(6);
  await expect(browser.getByRole('button', { name: 'Character', exact: true })).toHaveCount(0);
  await browser.getByRole('button', { name: 'Mara the innkeeper', exact: true }).click();
  await expect(browser.locator('[aria-current="page"]')).toHaveText('Mara the innkeeper');
  await expect(page.getByRole('checkbox', { name: 'WalkThrough', exact: true })).toBeVisible();
  await browser.getByRole('button', { name: 'Characters', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Pointlesh properties', exact: true })).toBeHidden();
  await browser.getByRole('button', { name: 'Prefabs', exact: true }).click();
  await expect(browser.getByRole('button', { name: 'Open Hotspots folder' })).toHaveCount(0);
  await expect(browser.getByRole('button', { name: 'Open Areas folder' })).toHaveCount(0);
  await selectInstance(page, 'village.borin');
  await page.getByRole('button', { name: 'Edit prefab', exact: true }).click();
  await expect(browser.locator('[aria-current="page"]')).toHaveText('Borin');
  await expect(browser.getByRole('button', { name: 'Characters', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('create a named prefab from its hidden template, undo/redo, then place it using folders', async ({ page }) => {
  await page.goto('/?designer=1'); await expect(page.locator('#loading')).toBeHidden();
  await page.getByRole('button', { name: 'Toggle prefab designer', exact: true }).click();
  const browser = page.getByRole('region', { name: 'Prefab browser', exact: true });
  await browser.getByRole('button', { name: 'Open Objects folder' }).click();
  await browser.getByRole('button', { name: 'New prefab', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'New prefab', exact: true });
  await expect(dialog.getByRole('combobox', { name: 'Prefab type' })).toHaveValue('pointlesh.object');
  await dialog.getByRole('textbox', { name: 'Prefab name' }).fill('Test lantern');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(browser.locator('[aria-current="page"]')).toHaveText('Test lantern');
  const id = await page.evaluate(() => (window as any).pointleshDemo.scene.sceneDesigner.designer.getSelectedPrefabId());
  await page.getByRole('region', { name: 'Pointlesh properties', exact: true }).getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await page.evaluate(id => !!(window as any).pointleshDemo.manifest.prefabs[id], id)).toBe(false);
  await page.evaluate(() => (window as any).pointleshDemo.scene.sceneDesigner.designer.redo());
  await browser.getByRole('button', { name: 'Prefabs', exact: true }).click();
  await browser.getByRole('button', { name: 'Open Objects folder' }).click();
  await expect(browser.getByRole('button', { name: 'Test lantern', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Toggle scene designer', exact: true }).click();
  await page.getByRole('button', { name: 'Add prefab', exact: true }).click();
  const picker = page.getByRole('region', { name: 'Choose prefab', exact: true });
  const add = page.locator('dialog').getByRole('button', { name: 'Add', exact: true });
  await expect(add).toBeDisabled();
  await picker.getByRole('button', { name: 'Open Objects folder' }).click();
  await expect(picker.getByRole('button', { name: 'Object', exact: true })).toHaveCount(0);
  await picker.getByRole('button', { name: 'Test lantern', exact: true }).click();
  await add.click();
  await expect.poll(() => page.evaluate(id => (window as any).pointleshDemo.manifest.scenes.village.layers.flatMap((layer: any) => layer.prefabs ?? []).some((instance: any) => instance.prefabId === id), id)).toBe(true);
});
